<?php

const STATUS_OK = 0x0;
const STATUS_FAIL = 0x1;
const STATUS_FORBIDDEN = 0x2;
const STATUS_NOT_SUPPORT = 0x3;
const METHOD_FETCH = 0x4;
const METHOD_UPDATE = 0x5;
const METHOD_INSERT = 0x6;
const METHOD_DELETE = 0x7;
const STATUS_UNDEFINED_METHOD = 0x8;
const STATUS_CORRUPTED_REQUEST = 0x9;
const STATUS_WRONG_ARGUMENT_TYPE = 0xA;
const STATUS_PLUGIN_NOT_FOUND = 0xB;